export const skillsTranslate = new Map([
    ['Backend', 'Backend'],
    ['Frontend', 'Frontend'],
    ['Analyst', 'Аналитик'],
    ['Manager', 'Менеджер'],
    ['Designer', 'Дизайнер'],
    ['Male', 'Мужчина'],
    ['Female', 'Женщина'],
    ['CSharp', 'CSharp'],
    ['React', 'React'],
    ['Java', 'Java'],
    ['PHP', 'PHP'],
    ['Figma', 'Figma'],
    ['Word', 'Word'],
])